---
title: "Data Wrangling"
author: "William DeForest, Nate Coffin, Ethan Dieck, Samantha Manywa"
date: "11/1/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


**Dataset creation using Excel**

```{r}
#load packages
library(dplyr)
library(tidyr)
library(tidyverse)
library(readxl)
library(ggplot2)
```


```{r}
AirTables_Data <- read_excel("C:\\Users\\wdd72\\OneDrive\\Documents\\Junior Fall\\Fintech Practicum\\Fintech_Data\\Companies-Fintech Practicum View.xlsx")
Unique_Obs <- read_excel("C:\\Users\\wdd72\\OneDrive\\Documents\\Junior Fall\\Fintech Practicum\\Fintech_Data\\Unique_Company_Founder_Obs.xlsx")
PDL_Data <- read_excel("C:\\Users\\wdd72\\OneDrive\\Documents\\Junior Fall\\Fintech Practicum\\Fintech_Data\\Final Clean PDL Data.xlsx")
DummyVars <- read_excel("C:\\Users\\wdd72\\OneDrive\\Documents\\Junior Fall\\Fintech Practicum\\Fintech_Data\\Dummy Variables 10.7.21.xlsx")
ConcatData <- read_excel("C:\\Users\\wdd72\\OneDrive\\Documents\\Junior Fall\\Fintech Practicum\\Fintech_Data\\Concatenated_Vars.xlsx")
Success_Measures <- read_excel("C:\\Users\\wdd72\\OneDrive\\Documents\\Junior Fall\\Fintech Practicum\\Fintech_Data\\Success Measures.xlsx")
```
```{r}
Unique_Obs$founders_lower <- tolower(Unique_Obs$Founders)
Unique_Obs_PDL <- left_join(Unique_Obs, PDL_Data, by=c("founders_lower"="full_name"))
Unique_Obs_PDL
```

```{r}
Combined_Data <- left_join(Unique_Obs_PDL, AirTables_Data, by=c("Company"="Name"))
Combined_Data
```

```{r}
Combo_Dummys <- left_join(Combined_Data, DummyVars, by=c("founders_lower"="FOUNDER"))
Combo_Dummys
```

```{r}
ConcatVars <- ConcatData %>% select(name...1, Company, company:major)
Combo_Dummy_Concat <- left_join(Combo_Dummys, ConcatVars, by=c("founders_lower"="name...1", "Company"="Company"))
```


```{r}
Combined_Data_Success_Dummies <- left_join(Combo_Dummy_Concat, Success_Measures, by=c("Company"="Company", "Founders.x"="Founders"))
Combined_Data_Success_Dummies <- Combined_Data_Success_Dummies %>% mutate(standard_Total_Capital_Raised = (Total_Capital_Raised - mean(Total_Capital_Raised))/sd(Total_Capital_Raised), standard_Product_Market_Fit = (Product_Market_Fit - mean(Product_Market_Fit))/sd(Product_Market_Fit), standard_Total_Financing_Rounds = (Total_Financing_Rounds - mean(Total_Financing_Rounds))/sd(Total_Financing_Rounds), standard_Liquidity_Event_Reached = (Liquidity_Event_Reached - mean(Liquidity_Event_Reached))/sd(Liquidity_Event_Reached), standard_length_of_company_life = (length_of_company_life - mean(length_of_company_life, na.rm=TRUE))/sd(length_of_company_life, na.rm=TRUE), standard_Total_Top_VCs = (Total_Top_VCs - mean(Total_Top_VCs))/sd(Total_Top_VCs))

Combined_Data_Success_Dummies <- Combined_Data_Success_Dummies %>% group_by(Company) %>% mutate(Combined_Success_Measure = sum(standard_Total_Capital_Raised, standard_Product_Market_Fit, standard_Total_Financing_Rounds, standard_Liquidity_Event_Reached, standard_length_of_company_life, standard_Total_Top_VCs, na.rm=TRUE))
```

```{r}
#Create time since graduation variable and dummy variable for missing grad year
Combined_Data_Success_Dummies$`Grad Year of Founder`[is.na(Combined_Data_Success_Dummies$`Grad Year of Founder`)] <- 0

Combined_Data_Success_Dummies$`Grad Year of Founder` <- Combined_Data_Success_Dummies$`Grad Year of Founder` %>% str_remove_all(", .{0,4}") %>% as.numeric()

Combined_Data_Success_Dummies <- Combined_Data_Success_Dummies %>% mutate(missing_grad_year = ifelse(`Grad Year of Founder`== "0", 1,0))

Combined_Data_Success_Dummies <- Combined_Data_Success_Dummies %>% mutate(time_since_grad = ifelse(`Grad Year of Founder` != "0", 2021-`Grad Year of Founder`, 0))
```


```{r}
write.csv(Combined_Data,"C:\\Users\\wdd72\\OneDrive\\Documents\\Junior Fall\\Fintech Practicum\\Fintech_Data\\Master_Combined_Data.csv", row.names = FALSE)
```

```{r}
write.csv(Combo_Dummys,"C:\\Users\\wdd72\\OneDrive\\Documents\\Junior Fall\\Fintech Practicum\\Fintech_Data\\Combined_with_Dummies.csv", row.names = FALSE)
```

```{r}
write.csv(Unique_Obs_PDL,"C:\\Users\\wdd72\\OneDrive\\Documents\\Junior Fall\\Fintech Practicum\\Fintech_Data\\Unique_Obs_PDL.csv", row.names = FALSE)
```

```{r}
write.csv(Combined_Data_Success_Dummies,"C:\\Users\\wdd72\\OneDrive\\Documents\\Junior Fall\\Fintech Practicum\\Fintech_Data\\Combined_Data_For_Regression_11.30.csv", row.names = FALSE)
```

```{r}
#summary statistics - School

School_Obs <- Combined_Data_Success_Dummies %>% select(Company, CMC_Dummy, Pomona_Dummy, Scripps_Dummy, Pitzer_Dummy, HMC_Dummy)

  
School_Obs_Narrow <- gather(School_Obs, key="school", value="Dummy", CMC_Dummy, Pomona_Dummy, Scripps_Dummy, Pitzer_Dummy, HMC_Dummy)


School_5C_Summary <- School_Obs_Narrow %>% group_by(school) %>% replace(is.na(.), 0) %>% summarize(Number_of_Founders=sum(Dummy))
School_5C_Summary
```

```{r}
#summary statistics - Industry
Industry_Obs <- Combined_Data_Success_Dummies %>% select(Company, Energy_dummy, Materials_dummy, Industrials_dummy, Utilities_dummy, Healthcare_dummy, Financials_dummy, Information_Technology_dummy, Communication_Services_dummy, Real_Estate_dummy, Food_Production_Distribution_dummy, Fine_Arts_dummy, Retail_dummy, Education_dummy, Professional_services_dummy, Entertainment_dummy, Hospitality_Recreation_dummy, Government_dummy, Public_Service_dummy)
Industry_Obs

Industry_Obs_Narrow <- gather(Industry_Obs, key="industry", value="Dummy", Energy_dummy, Materials_dummy, Industrials_dummy, Utilities_dummy, Healthcare_dummy, Financials_dummy, Information_Technology_dummy, Communication_Services_dummy, Real_Estate_dummy, Food_Production_Distribution_dummy, Fine_Arts_dummy, Retail_dummy, Education_dummy, Professional_services_dummy, Entertainment_dummy, Hospitality_Recreation_dummy, Government_dummy, Public_Service_dummy)
Industry_Obs_Narrow

Industry_Summary <- Industry_Obs_Narrow %>% group_by(industry) %>% replace(is.na(.), 0) %>% summarize(Number_of_Founders=sum(Dummy)) %>% arrange(desc(Number_of_Founders))
Industry_Summary
```

```{r}
#non-standardized success variables distributions

hist_total_capital_raised <- ggplot(data=Combined_Data_Success_Dummies, aes(x=Total_Capital_Raised)) + geom_histogram()
hist_total_capital_raised

hist_Product_Market_Fit <- ggplot(data=Combined_Data_Success_Dummies, aes(x=Product_Market_Fit)) + geom_histogram()
hist_Product_Market_Fit

hist_Total_Financing_Rounds <- ggplot(data=Combined_Data_Success_Dummies, aes(x=Total_Financing_Rounds)) + geom_histogram()
hist_Total_Financing_Rounds

hist_Liquidity_Event_Reached <- ggplot(data=Combined_Data_Success_Dummies, aes(x=Liquidity_Event_Reached)) + geom_histogram()
hist_Liquidity_Event_Reached

hist_length_of_company_life <- ggplot(data=Combined_Data_Success_Dummies, aes(x=length_of_company_life)) + geom_histogram()
hist_length_of_company_life

hist_Total_Top_VCs <- ggplot(data=Combined_Data_Success_Dummies, aes(x=Total_Top_VCs)) + geom_histogram()
hist_Total_Top_VCs
```


```{r}
#Standardized Success variable distributions

dist_total_capital_raised <- ggplot(data=Combined_Data_Success_Dummies, aes(x=standard_Total_Capital_Raised)) + geom_histogram()
dist_total_capital_raised

dist_Product_Market_Fit <- ggplot(data=Combined_Data_Success_Dummies, aes(x=standard_Product_Market_Fit)) + geom_histogram()
dist_Product_Market_Fit

dist_Total_Financing_Rounds <- ggplot(data=Combined_Data_Success_Dummies, aes(x=standard_Total_Financing_Rounds)) + geom_histogram()
dist_Total_Financing_Rounds

dist_Liquidity_Event_Reached <- ggplot(data=Combined_Data_Success_Dummies, aes(x=standard_Liquidity_Event_Reached)) + geom_histogram()
dist_Liquidity_Event_Reached

dist_length_of_company_life <- ggplot(data=Combined_Data_Success_Dummies, aes(x=standard_length_of_company_life)) + geom_histogram()
dist_length_of_company_life

dist_Total_Top_VCs <- ggplot(data=Combined_Data_Success_Dummies, aes(x=standard_Total_Top_VCs)) + geom_histogram()
dist_Total_Top_VCs

dist_Combined_Success_Measure <- ggplot(data=Combined_Data_Success_Dummies, aes(x=Combined_Success_Measure)) + geom_histogram()
dist_Combined_Success_Measure

```

```{r}
#Data with outliers removed. Outliers defined as observations with a Combined_Success_Measure greater than 3x the standard deviation of the Combined_Success_Measure.

Data_No_Outliers <- Combined_Data_Success_Dummies %>% group_by(Company) %>% filter(!(Combined_Success_Measure >= sd(Combined_Data_Success_Dummies$Combined_Success_Measure)*3))

write.csv(Data_No_Outliers,"C:\\Users\\wdd72\\OneDrive\\Documents\\Junior Fall\\Fintech Practicum\\Fintech_Data\\Combined_Data_For_Regression_No_Outliers_11.30.csv", row.names = FALSE)
```

```{r}
#Standardized Success variable distributions with outliers removed

dist_total_capital_raised_no_out <- ggplot(data=Data_No_Outliers, aes(x=standard_Total_Capital_Raised)) + geom_histogram()
dist_total_capital_raised_no_out

dist_Product_Market_Fit_no_out <- ggplot(data=Data_No_Outliers, aes(x=standard_Product_Market_Fit)) + geom_histogram()
dist_Product_Market_Fit_no_out

dist_Total_Financing_Rounds_no_out <- ggplot(data=Data_No_Outliers, aes(x=standard_Total_Financing_Rounds)) + geom_histogram()
dist_Total_Financing_Rounds_no_out

dist_Liquidity_Event_Reached_no_out <- ggplot(data=Data_No_Outliers, aes(x=standard_Liquidity_Event_Reached)) + geom_histogram()
dist_Liquidity_Event_Reached_no_out

dist_length_of_company_life_no_out <- ggplot(data=Data_No_Outliers, aes(x=standard_length_of_company_life)) + geom_histogram()
dist_length_of_company_life_no_out

dist_Total_Top_VCs_no_out <- ggplot(data=Data_No_Outliers, aes(x=standard_Total_Top_VCs)) + geom_histogram()
dist_Total_Top_VCs_no_out

dist_Combined_Success_Measure_no_out <- ggplot(data=Data_No_Outliers, aes(x=Combined_Success_Measure)) + geom_histogram()
dist_Combined_Success_Measure_no_out

```

